version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-web
    container_name: my-web-container
    ports:
      - "5000:5000"
    volumes:
      # - ./data:/my-data
      - ./templates:/app/templates

